name: call-workflow

on: 
    pull_request:
        branches: [ "main" ]

jobs:
    call-another-workflow:
        uses: ./.github/workflows/call_workflow.yml
        with:
            environment: Development
        secrets:
            DOCKER_USERNAME: Jatin Kaushik