name: testing-actions

on:
    workflow_dispatch:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
        secrets:
            DOCKER_USERNAME:
                required: true


jobs:
    run-manually:
     runs-on: ubuntu-latest
     steps:
      - name: Print Environment
        run: echo "Running on environment- ${{inputs.environment}}"
      - name: Print Secret
        run: echo "The docker name is - ${{secrets.DOCKER_USERNAME}}"